# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'infoAboutPriem.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_infoAboutPriem(object):
    def setupUi(self, infoAboutPriem):
        infoAboutPriem.setObjectName("infoAboutPriem")
        infoAboutPriem.resize(844, 600)
        self.centralwidget = QtWidgets.QWidget(infoAboutPriem)
        self.centralwidget.setObjectName("centralwidget")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(10, 50, 211, 161))
        self.listView.setObjectName("listView")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 211, 21))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"gridline-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 220, 211, 41))
        self.pushButton.setObjectName("pushButton")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(230, 20, 601, 561))
        self.plainTextEdit.setObjectName("plainTextEdit")
        infoAboutPriem.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(infoAboutPriem)
        self.statusbar.setObjectName("statusbar")
        infoAboutPriem.setStatusBar(self.statusbar)

        self.retranslateUi(infoAboutPriem)
        QtCore.QMetaObject.connectSlotsByName(infoAboutPriem)

    def retranslateUi(self, infoAboutPriem):
        _translate = QtCore.QCoreApplication.translate
        infoAboutPriem.setWindowTitle(_translate("infoAboutPriem", "Информация о приеме"))
        self.pushButton.setText(_translate("infoAboutPriem", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    infoAboutPriem = QtWidgets.QMainWindow()
    ui = Ui_infoAboutPriem()
    ui.setupUi(infoAboutPriem)
    infoAboutPriem.show()
    sys.exit(app.exec_())
