# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TODO.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TODO(object):
    def setupUi(self, TODO):
        TODO.setObjectName("TODO")
        TODO.resize(1071, 843)
        self.centralwidget = QtWidgets.QWidget(TODO)
        self.centralwidget.setObjectName("centralwidget")
        self.loaderPacientB = QtWidgets.QPushButton(self.centralwidget)
        self.loaderPacientB.setGeometry(QtCore.QRect(10, 200, 141, 61))
        self.loaderPacientB.setObjectName("loaderPacientB")
        self.delPriem = QtWidgets.QPushButton(self.centralwidget)
        self.delPriem.setGeometry(QtCore.QRect(150, 200, 61, 61))
        self.delPriem.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Изображения/1345823.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delPriem.setIcon(icon)
        self.delPriem.setObjectName("delPriem")
        self.textNewDrugs = QtWidgets.QLineEdit(self.centralwidget)
        self.textNewDrugs.setGeometry(QtCore.QRect(760, 160, 301, 23))
        self.textNewDrugs.setObjectName("textNewDrugs")
        self.senderDrugs = QtWidgets.QPushButton(self.centralwidget)
        self.senderDrugs.setGeometry(QtCore.QRect(760, 180, 301, 23))
        self.senderDrugs.setObjectName("senderDrugs")
        self.sender = QtWidgets.QPushButton(self.centralwidget)
        self.sender.setGeometry(QtCore.QRect(760, 732, 301, 61))
        self.sender.setObjectName("sender")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 201, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 270, 201, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 550, 201, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(220, 10, 211, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(760, 10, 171, 16))
        self.label_5.setObjectName("label_5")
        self.deagnosesList = QtWidgets.QListWidget(self.centralwidget)
        self.deagnosesList.setGeometry(QtCore.QRect(760, 230, 301, 301))
        self.deagnosesList.setObjectName("deagnosesList")
        self.getterinfoAboutDiagnoses = QtWidgets.QPushButton(self.centralwidget)
        self.getterinfoAboutDiagnoses.setGeometry(QtCore.QRect(760, 540, 301, 51))
        self.getterinfoAboutDiagnoses.setObjectName("getterinfoAboutDiagnoses")
        self.newDiagnoses = QtWidgets.QLineEdit(self.centralwidget)
        self.newDiagnoses.setGeometry(QtCore.QRect(760, 690, 301, 31))
        self.newDiagnoses.setObjectName("newDiagnoses")
        self.textAbout = QtWidgets.QTextEdit(self.centralwidget)
        self.textAbout.setGeometry(QtCore.QRect(230, 29, 511, 771))
        self.textAbout.setObjectName("textAbout")
        self.listTODO = QtWidgets.QListWidget(self.centralwidget)
        self.listTODO.setGeometry(QtCore.QRect(10, 31, 201, 171))
        self.listTODO.setObjectName("listTODO")
        self.listDrugs = QtWidgets.QListWidget(self.centralwidget)
        self.listDrugs.setGeometry(QtCore.QRect(10, 570, 201, 231))
        self.listDrugs.setObjectName("listDrugs")
        self.listHistory = QtWidgets.QListWidget(self.centralwidget)
        self.listHistory.setGeometry(QtCore.QRect(10, 290, 201, 251))
        self.listHistory.setObjectName("listHistory")
        self.newDrugs = QtWidgets.QListWidget(self.centralwidget)
        self.newDrugs.setGeometry(QtCore.QRect(760, 30, 301, 131))
        self.newDrugs.setObjectName("newDrugs")
        TODO.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(TODO)
        self.statusbar.setObjectName("statusbar")
        TODO.setStatusBar(self.statusbar)

        self.retranslateUi(TODO)
        QtCore.QMetaObject.connectSlotsByName(TODO)

    def retranslateUi(self, TODO):
        _translate = QtCore.QCoreApplication.translate
        TODO.setWindowTitle(_translate("TODO", "Приемы"))
        self.loaderPacientB.setText(_translate("TODO", "Загрузить"))
        self.senderDrugs.setText(_translate("TODO", "Добавить"))
        self.sender.setText(_translate("TODO", "Отправка"))
        self.label.setText(_translate("TODO", "Приемы на сегодня"))
        self.label_2.setText(_translate("TODO", "Другие записи врачей"))
        self.label_3.setText(_translate("TODO", "Лекарства"))
        self.label_4.setText(_translate("TODO", "Запись приема"))
        self.label_5.setText(_translate("TODO", "Назначить лекарства"))
        self.getterinfoAboutDiagnoses.setText(_translate("TODO", "Подробней"))