# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'verefication.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Verification(object):
    def setupUi(self, Verification):
        Verification.setObjectName("Verification")
        Verification.resize(377, 145)
        self.centralwidget = QtWidgets.QWidget(Verification)
        self.centralwidget.setObjectName("centralwidget")
        self.textName = QtWidgets.QTextEdit(self.centralwidget)
        self.textName.setGeometry(QtCore.QRect(10, 10, 361, 31))
        self.textName.setObjectName("textName")
        self.Pasword = QtWidgets.QTextEdit(self.centralwidget)
        self.Pasword.setGeometry(QtCore.QRect(10, 50, 361, 31))
        self.Pasword.setObjectName("Pasword")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 90, 361, 23))
        self.pushButton.setObjectName("pushButton")
        Verification.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Verification)
        self.statusbar.setObjectName("statusbar")
        Verification.setStatusBar(self.statusbar)

        self.retranslateUi(Verification)
        QtCore.QMetaObject.connectSlotsByName(Verification)

    def retranslateUi(self, Verification):
        _translate = QtCore.QCoreApplication.translate
        Verification.setWindowTitle(_translate("Verification", "Вход"))
        self.textName.setPlaceholderText(_translate("Verification", "ФИО"))
        self.Pasword.setPlaceholderText(_translate("Verification", "Пароль"))
        self.pushButton.setText(_translate("Verification", "войти"))


